/**
 * SubstrateGovernanceActionsAdapter
 *
 * Implements GovernanceActionsPort for vibly-chain solo-node OpenGov
 * using polkadot-api (PAPI).
 *
 * Design notes
 * ─────────────
 * • PAPI requires a "descriptor" package generated by `papi add` (codegen).
 *   Until codegen is run against the vibly-chain solo-node, we use the
 *   generic low-level PAPI client (PolkadotClient / createClient) with
 *   dynamic extrinsic construction via `tx.<pallet>.<call>`.
 * • The signer is injected as a PolkadotSigner; callers are responsible
 *   for deriving it from a mnemonic / dev account via
 *   `polkadot-api/accounts` or `@polkadot-api/signer`.
 * • This adapter is intentionally minimal: it covers the lifecycle
 *   needed by Phase B (prepare + cast vote, delegate, undelegate,
 *   unlockOrReclaim). Proposal submission is out-of-scope for Phase B.
 */

import type {
  GovernanceActionsPort,
  GovernanceSubjectRef,
  GovernanceVoteStance,
  GovernanceProposalSummary,
} from "@concord/governance";
import type { ChainRef, TxReceipt } from "@concord/core";
import type { SubstrateActionsConfig } from "./types.js";

// ─── PAPI lazy import ─────────────────────────────────────────────────────────
// polkadot-api is an optional peer; we import dynamically so the package can
// still be type-checked without a live chain.

type PapiClient = import("polkadot-api").PolkadotClient;
type PapiSigner = import("polkadot-api").PolkadotSigner;

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toTxReceipt(txHash: string, chain: ChainRef, blockHash?: string): TxReceipt {
  return {
    txHash,
    chain,
    blockHash,
    finality: "included",
  };
}

const NEEDS_CODEGEN =
  "This method requires PAPI descriptors generated via:\n" +
  "  pnpm dlx @polkadot-api/cli add vibly-solo --wsUrl ws://127.0.0.1:9944\n" +
  "After codegen, replace the typed API calls in governance.ts.";

const NO_SIGNER =
  "SubstrateGovernanceActionsAdapter: no signer configured. " +
  "Pass a PolkadotSigner in config.signer (see types.ts for instructions).";

// ─── Adapter ──────────────────────────────────────────────────────────────────

export class SubstrateGovernanceActionsAdapter implements GovernanceActionsPort {
  readonly kind = "substrate-opengov" as const;

  private readonly config: { rpcUrl: string; signer?: PapiSigner; chainId: string };
  private _client: PapiClient | null = null;

  constructor(config: SubstrateActionsConfig = {}) {
    this.config = {
      rpcUrl: config.rpcUrl ?? "ws://127.0.0.1:9944",
      signer: config.signer,
      chainId: config.chainId ?? "substrate:vibly-solo",
    };
  }

  // ── Lazy PAPI client initialization ─────────────────────────────────────────

  private async getClient(): Promise<PapiClient> {
    if (this._client) return this._client;
    const { createClient } = await import("polkadot-api");
    const { getWsProvider } = await import("polkadot-api/ws-provider/node");
    this._client = createClient(getWsProvider(this.config.rpcUrl));
    return this._client;
  }

  private getSigner(): PapiSigner {
    if (!this.config.signer) throw new Error(NO_SIGNER);
    return this.config.signer;
  }

  // ── GovernanceActionsPort ────────────────────────────────────────────────────

  async prepareProposal(input: {
    chain: ChainRef;
    actor: string;
    title: string;
    description?: string;
    metadata?: Record<string, unknown>;
  }): Promise<{
    chain: ChainRef;
    actor: string;
    payload: unknown;
    summary: GovernanceProposalSummary;
  }> {
    // Phase B: prepare-only (no submission), return structured payload
    const payload = {
      type: "substrate-opengov-submit-referendum",
      title: input.title,
      description: input.description,
      metadata: input.metadata,
    };
    const summary: GovernanceProposalSummary = {
      ref: {
        chain: input.chain,
        backend: "substrate-opengov",
        externalId: "pending",
      },
      title: input.title,
      status: "draft",
      metadata: input.metadata,
    };
    return { chain: input.chain, actor: input.actor, payload, summary };
  }

  async submitProposal(input: {
    chain: ChainRef;
    actor: string;
    payload: unknown;
  }): Promise<TxReceipt> {
    // Full referendum submission requires a preimage + referenda.submit call.
    // Out of scope for Phase B — throw a descriptive error.
    throw new Error(
      "SubstrateGovernanceActionsAdapter.submitProposal: not implemented in Phase B. " +
        "Use the vibly-chain governance UI or a direct PAPI script.",
    );
  }

  async prepareVote(input: {
    subject: GovernanceSubjectRef;
    voter: string;
    stance: GovernanceVoteStance;
    weight?: string;
    reason?: string;
    metadata?: Record<string, unknown>;
  }): Promise<{
    subject: GovernanceSubjectRef;
    voter: string;
    payload: unknown;
  }> {
    const conviction = Number(
      (input.metadata?.["conviction"] as string | number | undefined) ?? 0,
    );
    const balance = BigInt(input.weight ?? "1000000000"); // 1 UNIT default
    const payload = {
      type: "convictionVoting.vote",
      pollIndex: Number(input.subject.externalId),
      vote: encodeAccountVote(input.stance, conviction, balance),
    };
    return { subject: input.subject, voter: input.voter, payload };
  }

  async castVote(input: {
    subject: GovernanceSubjectRef;
    voter: string;
    payload: unknown;
  }): Promise<TxReceipt> {
    // Requires PAPI codegen descriptors to call typed extrinsics.
    // Run `pnpm dlx @polkadot-api/cli add vibly-solo --wsUrl ws://127.0.0.1:9944`
    // to generate descriptors and implement typed convictionVoting.vote() here.
    void this.getClient(); // validate rpcUrl format eagerly
    void this.getSigner(); // validate signer is configured
    throw new Error(`castVote: ${NEEDS_CODEGEN}`);
  }

  async delegate(input: {
    chain: ChainRef;
    delegator: string;
    delegatee: string;
    scope?: string;
    conviction?: string;
    metadata?: Record<string, unknown>;
  }): Promise<TxReceipt> {
    void this.getSigner();
    throw new Error(`delegate: ${NEEDS_CODEGEN}`);
  }

  async undelegate(input: {
    chain: ChainRef;
    delegator: string;
    scope?: string;
  }): Promise<TxReceipt> {
    void this.getSigner();
    throw new Error(`undelegate: ${NEEDS_CODEGEN}`);
  }

  async unlockOrReclaim(input: {
    chain: ChainRef;
    actor: string;
    subject?: GovernanceSubjectRef;
  }): Promise<TxReceipt> {
    void this.getSigner();
    throw new Error(`unlockOrReclaim: ${NEEDS_CODEGEN}`);
  }

  /** Gracefully disconnect the PAPI WebSocket. */
  async destroy(): Promise<void> {
    if (this._client) {
      this._client.destroy();
      this._client = null;
    }
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function encodeAccountVote(
  stance: GovernanceVoteStance,
  conviction: number,
  balance: bigint,
): unknown {
  switch (stance) {
    case "aye":
    case "support":
      return {
        type: "Standard",
        value: {
          vote: { aye: true, conviction: convictionEnum(conviction) },
          balance,
        },
      };
    case "nay":
    case "oppose":
      return {
        type: "Standard",
        value: {
          vote: { aye: false, conviction: convictionEnum(conviction) },
          balance,
        },
      };
    case "abstain":
      return {
        type: "SplitAbstain",
        value: { aye: BigInt(0), nay: BigInt(0), abstain: balance },
      };
    case "split":
      return {
        type: "Split",
        value: { aye: balance / BigInt(2), nay: balance / BigInt(2) },
      };
    default:
      throw new Error(`Unknown stance: ${stance as string}`);
  }
}

function convictionEnum(n: number): string {
  const map: Record<number, string> = {
    0: "None",
    1: "Locked1x",
    2: "Locked2x",
    3: "Locked3x",
    4: "Locked4x",
    5: "Locked5x",
    6: "Locked6x",
  };
  return map[n] ?? "None";
}

function parseConviction(s: string): string {
  if (/^\d+$/.test(s)) return convictionEnum(Number(s));
  return s;
}
