/**
 * SubstrateGovernanceActionsAdapter
 *
 * Implements GovernanceActionsPort for vibly-chain solo-node OpenGov
 * using polkadot-api (PAPI).
 *
 * Design notes
 * ─────────────
 * • PAPI requires a "descriptor" package generated by `papi add` (codegen).
 *   Until codegen is run against the vibly-chain solo-node, we use the
 *   generic low-level PAPI client (PolkadotClient / createClient) with
 *   dynamic extrinsic construction via `tx.<pallet>.<call>`.
 * • The signer is injected as a PolkadotSigner; callers are responsible
 *   for deriving it from a mnemonic / dev account via
 *   `polkadot-api/accounts` or `@polkadot-api/signer`.
 * • This adapter is intentionally minimal: it covers the lifecycle
 *   needed by Phase B (prepare + cast vote, delegate, undelegate,
 *   unlockOrReclaim). Proposal submission is out-of-scope for Phase B.
 */

import type {
  GovernanceActionsPort,
  GovernanceSubjectRef,
  GovernanceVoteStance,
  GovernanceProposalSummary,
} from "@vibly-ai/concord-governance";
import type { ChainRef, TxReceipt } from "@vibly-ai/concord-core";
import type { SubstrateActionsConfig, SubstrateTxSubmitter } from "./types.js";

// ─── PAPI lazy import ─────────────────────────────────────────────────────────
// polkadot-api is an optional peer; we import dynamically so the package can
// still be type-checked without a live chain.

type PapiClient = import("polkadot-api").PolkadotClient;
type PapiSigner = import("polkadot-api").PolkadotSigner;
type PapiTxFinalizedPayload = {
  txHash: string;
  ok?: boolean;
  block?: { hash?: string; number?: number | bigint };
};

// ─── Helpers ──────────────────────────────────────────────────────────────────

function toTxReceipt(
  txHash: string,
  chain: ChainRef,
  blockHash?: string,
  blockNumber?: number | bigint,
  finality: TxReceipt["finality"] = "included",
): TxReceipt {
  const receipt: TxReceipt = {
    txHash,
    chain,
    finality,
  };
  if (blockHash !== undefined) receipt.blockHash = blockHash;
  if (blockNumber !== undefined) receipt.blockNumber = BigInt(blockNumber);
  return receipt;
}

const NEEDS_SUBMITTER =
  "SubstrateGovernanceActionsAdapter: no transaction submitter configured. " +
  "Provide config.submitter from generated PAPI bindings, or enable the " +
  "experimental unsafe PAPI submit path with config.signer.";

const NO_SIGNER =
  "SubstrateGovernanceActionsAdapter: no signer configured. " +
  "Pass a PolkadotSigner in config.signer (see types.ts for instructions).";

// ─── Adapter ──────────────────────────────────────────────────────────────────

export class SubstrateGovernanceActionsAdapter implements GovernanceActionsPort {
  readonly kind = "substrate-opengov" as const;

  private readonly config: { rpcUrl: string; signer?: PapiSigner; chainId: string; submitter?: SubstrateTxSubmitter };
  private _client: PapiClient | null = null;

  constructor(config: SubstrateActionsConfig = {}) {
    this.config = {
      rpcUrl: config.rpcUrl ?? "ws://127.0.0.1:9944",
      chainId: config.chainId ?? "substrate:vibly-solo",
    };
    if (config.signer !== undefined) this.config.signer = config.signer;
    if (config.submitter !== undefined) this.config.submitter = config.submitter;
  }

  // ── Lazy PAPI client initialization ─────────────────────────────────────────

  private async getClient(): Promise<PapiClient> {
    if (this._client) return this._client;
    const { createClient } = await import("polkadot-api");
    const { getWsProvider } = await import("polkadot-api/ws-provider/node");
    this._client = createClient(getWsProvider(this.config.rpcUrl));
    return this._client;
  }

  private getSigner(): PapiSigner {
    if (!this.config.signer) throw new Error(NO_SIGNER);
    return this.config.signer;
  }

  // ── GovernanceActionsPort ────────────────────────────────────────────────────

  async prepareProposal(input: {
    chain: ChainRef;
    actor: string;
    title: string;
    description?: string;
    metadata?: Record<string, unknown>;
  }): Promise<{
    chain: ChainRef;
    actor: string;
    payload: unknown;
    summary: GovernanceProposalSummary;
  }> {
    const payload: Record<string, unknown> = {
      type: "substrate-opengov-submit-referendum",
      pallet: "Referenda",
      call: "submit",
      title: input.title,
      args: input.metadata?.["submitArgs"] ?? input.metadata?.["args"] ?? null,
    };
    if (input.description !== undefined) payload["description"] = input.description;
    if (input.metadata !== undefined) payload["metadata"] = input.metadata;
    const summary: GovernanceProposalSummary = {
      ref: {
        chain: input.chain,
        backend: "substrate-opengov",
        externalId: "pending",
      },
      title: input.title,
      status: "draft",
    };
    if (input.metadata !== undefined) summary.metadata = input.metadata;
    return { chain: input.chain, actor: input.actor, payload, summary };
  }

  async submitProposal(input: {
    chain: ChainRef;
    actor: string;
    payload: unknown;
  }): Promise<TxReceipt> {
    const tx = normalizeTxPayload(input.payload, {
      pallet: "Referenda",
      call: "submit",
      fallbackArgs: asRecord(input.payload)["args"],
    });
    return this.submitGovernanceTx({
      chain: input.chain,
      actor: input.actor,
      payload: input.payload,
      ...tx,
    });
  }

  async prepareVote(input: {
    subject: GovernanceSubjectRef;
    voter: string;
    stance: GovernanceVoteStance;
    weight?: string;
    reason?: string;
    metadata?: Record<string, unknown>;
  }): Promise<{
    subject: GovernanceSubjectRef;
    voter: string;
    payload: unknown;
  }> {
    const conviction = Number(
      (input.metadata?.["conviction"] as string | number | undefined) ?? 0,
    );
    const balance = BigInt(input.weight ?? "1000000000"); // 1 UNIT default
    const payload = {
      type: "convictionVoting.vote",
      pallet: "ConvictionVoting",
      call: "vote",
      pollIndex: Number(input.subject.externalId),
      args: {
        poll_index: Number(input.subject.externalId),
        vote: encodeAccountVote(input.stance, conviction, balance),
      },
      vote: encodeAccountVote(input.stance, conviction, balance),
    };
    return { subject: input.subject, voter: input.voter, payload };
  }

  async castVote(input: {
    subject: GovernanceSubjectRef;
    voter: string;
    payload: unknown;
  }): Promise<TxReceipt> {
    const tx = normalizeTxPayload(input.payload, {
      pallet: "ConvictionVoting",
      call: "vote",
      fallbackArgs: asRecord(input.payload)["args"],
    });
    return this.submitGovernanceTx({
      chain: input.subject.chain,
      actor: input.voter,
      payload: input.payload,
      ...tx,
    });
  }

  async delegate(input: {
    chain: ChainRef;
    delegator: string;
    delegatee: string;
    scope?: string;
    conviction?: string;
    metadata?: Record<string, unknown>;
  }): Promise<TxReceipt> {
    const args = {
      class: Number(input.scope ?? "0"),
      to: input.delegatee,
      conviction: parseConviction(input.conviction ?? "0"),
      balance: BigInt(String(input.metadata?.["balance"] ?? "1000000000")),
    };
    return this.submitGovernanceTx({
      chain: input.chain,
      actor: input.delegator,
      pallet: "ConvictionVoting",
      call: "delegate",
      args,
      payload: { type: "convictionVoting.delegate", args },
    });
  }

  async undelegate(input: {
    chain: ChainRef;
    delegator: string;
    scope?: string;
  }): Promise<TxReceipt> {
    const args = { class: Number(input.scope ?? "0") };
    return this.submitGovernanceTx({
      chain: input.chain,
      actor: input.delegator,
      pallet: "ConvictionVoting",
      call: "undelegate",
      args,
      payload: { type: "convictionVoting.undelegate", args },
    });
  }

  async unlockOrReclaim(input: {
    chain: ChainRef;
    actor: string;
    subject?: GovernanceSubjectRef;
  }): Promise<TxReceipt> {
    const args = input.subject
      ? { class: 0, target: input.actor, index: Number(input.subject.externalId) }
      : { class: 0, target: input.actor };
    return this.submitGovernanceTx({
      chain: input.chain,
      actor: input.actor,
      pallet: "ConvictionVoting",
      call: "unlock",
      args,
      payload: { type: "convictionVoting.unlock", args },
    });
  }

  /** Gracefully disconnect the PAPI WebSocket. */
  async destroy(): Promise<void> {
    if (this._client) {
      this._client.destroy();
      this._client = null;
    }
  }

  private async submitGovernanceTx(input: {
    chain: ChainRef;
    actor: string;
    pallet: string;
    call: string;
    args: unknown;
    payload: unknown;
  }): Promise<TxReceipt> {
    if (this.config.submitter) return this.config.submitter(input);
    const signer = this.config.signer;
    if (!signer) throw new Error(NEEDS_SUBMITTER);
    const client = await this.getClient();
    const api = client.getUnsafeApi<unknown>();
    const palletApi = selectEntry(api.tx, input.pallet);
    const callApi = selectEntry(palletApi, input.call);
    if (typeof callApi !== "function") {
      throw new Error(`SubstrateGovernanceActionsAdapter: tx ${input.pallet}.${input.call} is not available`);
    }
    const tx = callApi(input.args) as { signAndSubmit?: (signer: PapiSigner) => Promise<PapiTxFinalizedPayload> };
    if (typeof tx.signAndSubmit !== "function") {
      throw new Error(`SubstrateGovernanceActionsAdapter: tx ${input.pallet}.${input.call} cannot be submitted`);
    }
    const result = await tx.signAndSubmit(signer);
    if (result.ok === false) {
      throw new Error(`SubstrateGovernanceActionsAdapter: tx ${input.pallet}.${input.call} failed on chain`);
    }
    return toTxReceipt(
      result.txHash,
      input.chain,
      result.block?.hash,
      result.block?.number,
      "finalized",
    );
  }
}

// ─── Internal helpers ─────────────────────────────────────────────────────────

function encodeAccountVote(
  stance: GovernanceVoteStance,
  conviction: number,
  balance: bigint,
): unknown {
  switch (stance) {
    case "aye":
    case "support":
      return {
        type: "Standard",
        value: {
          vote: { aye: true, conviction: convictionEnum(conviction) },
          balance,
        },
      };
    case "nay":
    case "oppose":
      return {
        type: "Standard",
        value: {
          vote: { aye: false, conviction: convictionEnum(conviction) },
          balance,
        },
      };
    case "abstain":
      return {
        type: "SplitAbstain",
        value: { aye: BigInt(0), nay: BigInt(0), abstain: balance },
      };
    case "split":
      return {
        type: "Split",
        value: { aye: balance / BigInt(2), nay: balance / BigInt(2) },
      };
    default:
      throw new Error(`Unknown stance: ${stance as string}`);
  }
}

function convictionEnum(n: number): string {
  const map: Record<number, string> = {
    0: "None",
    1: "Locked1x",
    2: "Locked2x",
    3: "Locked3x",
    4: "Locked4x",
    5: "Locked5x",
    6: "Locked6x",
  };
  return map[n] ?? "None";
}

function parseConviction(s: string): string {
  if (/^\d+$/.test(s)) return convictionEnum(Number(s));
  return s;
}

function normalizeTxPayload(
  payload: unknown,
  fallback: { pallet: string; call: string; fallbackArgs?: unknown },
): { pallet: string; call: string; args: unknown } {
  const record = asRecord(payload);
  return {
    pallet: String(record["pallet"] ?? fallback.pallet),
    call: String(record["call"] ?? fallback.call),
    args: record["args"] ?? fallback.fallbackArgs ?? {},
  };
}

function asRecord(value: unknown): Record<string, unknown> {
  return value && typeof value === "object" ? value as Record<string, unknown> : {};
}

function selectEntry(root: unknown, key: string): unknown {
  const record = asRecord(root);
  return record[key] ?? record[lowerFirst(key)] ?? record[upperFirst(key)];
}

function lowerFirst(value: string): string {
  return value.charAt(0).toLowerCase() + value.slice(1);
}

function upperFirst(value: string): string {
  return value.charAt(0).toUpperCase() + value.slice(1);
}
